# Generated by Django 6.1 on 2026-08-12 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "customer",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("role", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "employee",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "supplier",
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                ("discount_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("percent_off", models.DecimalField(decimal_places=2, max_digits=5)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "db_table": "discount",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("percent_off__gte", 0), ("percent_off__lte", 100)
                        ),
                        name="discount_percent_off_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="discount_end_after_start",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("barcode", models.CharField(max_length=50, unique=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="store.category",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="store.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("sale_id", models.AutoField(primary_key=True, serialize=False)),
                ("sale_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="store.customer",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="store.employee",
                    ),
                ),
            ],
            options={
                "db_table": "sale",
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                ("sale_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_items",
                        to="store.discount",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="store.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="store.sale",
                    ),
                ),
            ],
            options={
                "db_table": "sale_item",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("po_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Received", "Received"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=30,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="store.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyCard",
            fields=[
                ("card_id", models.AutoField(primary_key=True, serialize=False)),
                ("points_balance", models.IntegerField(default=0)),
                (
                    "issued_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_card",
                        to="store.customer",
                    ),
                ),
            ],
            options={
                "db_table": "loyalty_card",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("points_balance__gte", 0)),
                        name="loyalty_points_balance_gte_0",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("inventory_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity_on_hand", models.IntegerField(default=0)),
                ("reorder_level", models.IntegerField(default=10)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "db_table": "inventory",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity_on_hand__gte", 0)),
                        name="inventory_qty_on_hand_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reorder_level__gte", 0)),
                        name="inventory_reorder_level_gte_0",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                ("po_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="store.purchaseorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_items",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_item",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="po_item_quantity_gt_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("unit_cost__gte", 0)),
                        name="po_item_unit_cost_gte_0",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["sale_date"], name="idx_sale_date"),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="sale_total_amount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="sale_item_quantity_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_total__gte", 0)),
                name="sale_item_line_total_gte_0",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["order_date"], name="idx_po_date"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="idx_product_name"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="product_unit_price_gte_0",
            ),
        ),
    ]
