# Generated by Django 6.1 on 2026-08-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_remove_employee_phone_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
